import pytest


@pytest.fixture
def default_ega_dataset():
    """A dataset description as returned by the EGA metadata API, taken from the ticket."""
    return {
        "accession_id": "EGAD00001005083",
        "title": "300-Obese cohort gut microbiome data",
        "description": (
            "300-Obese cohort, Nijmegen, the Netherlands. Dataset contains gut microbiome data "
            "generated by metagenomic sequencing."
        ),
        "dataset_types": ["Whole genome sequencing"],
        "technologies": ["Illumina HiSeq 2000"],
        "num_samples": 297,
        "access_type": "controlled",
        "is_in_beacon": False,
        "is_released": True,
        "released_date": "2001-01-01T00:00:00+01:00",
        "is_deprecated": False,
        "policy_accession_id": "EGAP00001001117",
    }


@pytest.fixture
def missing_ega_dataset():
    """An EGA dataset description missing mandatory fields (title, description)."""
    return {
        "accession_id": "EGAD00001005083",
    }
